language: node_js
node_js:
- 11.10.1
cache:
  directories:
    - ~/.npm
    - ~/.cache
    - $CACHE_DIR

install:
  - yarn install

defaults: &defaults
  script:
      #   ## print all Travis environment variables for debugging
      - yarn start &
      # - yarn cypress:record:parallel --group $STAGE_NAME
      - yarn cypress:run
      # - yarn cypress:server:ci:parallel --group $STAGE_NAME
      # after all tests finish running we need
      # to kill all background jobs (like "npm start &")
      - kill $(jobs -p) || true

script:
  - yarn test
  - yarn run build

jobs:
    include:
        - script:
          name: 'Cypress Tests 1t thread'
          env:
              - STAGE_NAME="2x-electron on Travis CI"
              # - STAGE_NAME="feature"
              - CACHE_DIR=cache
          <<: *defaults
        - script:
          name: 'Cypress Tests 2t thread'
          env:
              - STAGE_NAME="2x-electron on Travis CI"
              # - STAGE_NAME="billing"
              - CACHE_DIR=cache
          <<: *defaults

deploy:
  provider: pages
  skip-cleanup: true
  github-token: $GITHUB_TOKEN
  keep_history: true
  local_dir: build
  on:
   branch: master